const sid = () => "CA" + Math.random().toString(36).slice(2, 14).toUpperCase();

export function getHappyPathScript() {
  const callSid = sid();
  return [
    [0,     { type: "call_start",  callSid, from: "+1 (512) 867-5309" }],
    [700,   { type: "step",     node: "caller",  status: "active",  message: "Incoming call connected" }],
    [1100,  { type: "step",     node: "twilio",  status: "active",  message: "Studio flow triggered — playing greeting" }],
    [1500,  { type: "audio",    speaker: "IVR",  text: "Welcome to Intuit Card Services. How can I help you?" }],
    [2200,  { type: "caller_word", word: "I'd",     final: false }],
    [2360,  { type: "caller_word", word: "like",    final: false }],
    [2520,  { type: "caller_word", word: "to",      final: false }],
    [2680,  { type: "caller_word", word: "report",  final: false }],
    [2840,  { type: "caller_word", word: "a",       final: false }],
    [3000,  { type: "caller_word", word: "lost",    final: false }],
    [3160,  { type: "caller_word", word: "card.",   final: true  }],
    [3500,  { type: "audio",    speaker: "IVR",  text: "Please confirm your name and last four digits of your social security number." }],
    [4800,  { type: "caller_word", word: "Josh",       final: false }],
    [4980,  { type: "caller_word", word: "Skifstrom",  final: false }],
    [5160,  { type: "caller_word", word: "5467.",      final: true  }],
    [5400,  { type: "step",     node: "gateway", status: "active",  message: "POST /ivr  {intent, callSid}" }],
    [5700,  { type: "step",     node: "lambda",  status: "active",  message: "handler() invoked — Node.js 20.x" }],
    [6000,  { type: "security", level: "INFO",   message: `parseIntent(): callSid=${callSid.slice(0,10)}… intent=lostStolen source=speech attempt=1` }],
    [6200,  { type: "security", level: "REDACT", message: "redactSensitiveData(): event.body → [REDACTED — raw Twilio body]" }],
    [6400,  { type: "agent",    agent: "SECURITY",   status: "active", message: "PII check: body field redacted before CloudWatch ✓" }],
    [6600,  { type: "step",     node: "dynamo",  status: "active",  message: "PutItem: {callSid, intent, attempt:1, ttl:+24h}" }],
    [6900,  { type: "step",     node: "dynamo",  status: "success", message: "Call state tracked ✓" }],
    [7100,  { type: "agent",    agent: "ARCHITECT",  status: "active", message: "Twilio → Gateway → Lambda path nominal ✓" }],
    [7300,  { type: "security", level: "INFO",   message: "validateAuth(): requesting credentials from Secrets Manager" }],
    [7500,  { type: "step",     node: "secrets", status: "active",  message: "GetSecretValue('fintech-ivr/card-backend')" }],
    [7900,  { type: "step",     node: "secrets", status: "success", message: "apiKey + cardBackendUrl retrieved ✓" }],
    [8100,  { type: "security", level: "INFO",   message: "Outbound payload: { token, intent } — no raw card data ✓" }],
    [8300,  { type: "step",     node: "backend", status: "active",  message: "POST /validate — tokenized data only" }],
    [9000,  { type: "step",     node: "backend", status: "success", message: "{ status: 'ok' } → auth_status: success" }],
    [9200,  { type: "security", level: "SUCCESS", message: "auth_status: success — LLM context received token only, not raw card data ✓" }],
    [9400,  { type: "agent",    agent: "DEVELOPER",  status: "done",   message: "Lambda 200 OK — handler executed cleanly ✓" }],
    [9600,  { type: "step",     node: "lambda",  status: "success", message: "TwiML confirmation built" }],
    [9800,  { type: "step",     node: "gateway", status: "success", message: "Response delivered ✓" }],
    [10000, { type: "step",     node: "twilio",  status: "success", message: "TwiML executed — playing confirmation" }],
    [10300, { type: "audio",    speaker: "IVR",  text: "Thank you! Your card has been successfully reported as lost or stolen. A replacement card will arrive in 5 to 7 business days. Thank you for calling Intuit Card Services." }],
    [12000, { type: "step",     node: "caller",  status: "success", message: "Confirmed — call ended" }],
    [12200, { type: "deflected" }],
    [12400, { type: "security", level: "SUCCESS", message: "Call deflected ✓  Amazon Connect queue not reached  Zero PII logged ✓" }],
    [12600, { type: "agent",    agent: "SECURITY",   status: "done",   message: "Zero sensitive data in logs ✓  PCI-DSS compliant ✓" }],
    [12800, { type: "agent",    agent: "ARCHITECT",  status: "done",   message: "Self-service complete — Connect untouched ✓" }],
    [13000, { type: "agent",    agent: "INTEGRATOR", status: "done",   message: "Warm handoff on standby — not triggered ✓" }],
    [13200, { type: "complete", scenario: "happy" }],
  ];
}
